# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HangmanGameScreen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameScreen(object):
    def setupUi(self, GameScreen):
        GameScreen.setObjectName("GameScreen")
        GameScreen.resize(900, 600)
        GameScreen.setMinimumSize(QtCore.QSize(900, 600))
        GameScreen.setAutoFillBackground(False)
        GameScreen.setStyleSheet("background-color: rgb(240, 231, 239);")
        #GameScreen.setSizeGripEnabled(False)
        self.wordLabel = QtWidgets.QLabel(GameScreen)
        self.wordLabel.setGeometry(QtCore.QRect(110, 360, 661, 131))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.wordLabel.setFont(font)
        self.wordLabel.setAutoFillBackground(False)
        self.wordLabel.setObjectName("wordLabel")
        self.attemptsLabel = QtWidgets.QLabel(GameScreen)
        self.attemptsLabel.setGeometry(QtCore.QRect(10, 500, 131, 31))
        self.attemptsLabel.setObjectName("attemptsLabel")
        self.usedLettersLabel = QtWidgets.QLabel(GameScreen)
        self.usedLettersLabel.setGeometry(QtCore.QRect(10, 550, 351, 31))
        self.usedLettersLabel.setAutoFillBackground(False)
        self.usedLettersLabel.setObjectName("usedLettersLabel")
        self.player1Hangman = QtWidgets.QLabel(GameScreen)
        self.player1Hangman.setGeometry(QtCore.QRect(160, -50, 161, 231))
        self.player1Hangman.setAutoFillBackground(False)
        self.player1Hangman.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.player1Hangman.setText("")
        self.player1Hangman.setObjectName("player1Hangman")
        self.playerHangman1 = QtWidgets.QLabel(GameScreen)
        self.playerHangman1.setGeometry(QtCore.QRect(30, 0, 140, 260))
        self.playerHangman1.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.playerHangman1.setText("")
        self.playerHangman1.setObjectName("playerHangman1")
        self.playerHangman2 = QtWidgets.QLabel(GameScreen)
        self.playerHangman2.setGeometry(QtCore.QRect(210, 0, 140, 260))
        self.playerHangman2.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.playerHangman2.setText("")
        self.playerHangman2.setObjectName("playerHangman2")
        self.playerHangman3 = QtWidgets.QLabel(GameScreen)
        self.playerHangman3.setGeometry(QtCore.QRect(380, 0, 140, 260))
        self.playerHangman3.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.playerHangman3.setText("")
        self.playerHangman3.setObjectName("playerHangman3")
        self.playerHangman4 = QtWidgets.QLabel(GameScreen)
        self.playerHangman4.setGeometry(QtCore.QRect(550, 0, 140, 260))
        self.playerHangman4.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.playerHangman4.setText("")
        self.playerHangman4.setObjectName("playerHangman4")
        self.playerHangman5 = QtWidgets.QLabel(GameScreen)
        self.playerHangman5.setGeometry(QtCore.QRect(730, 0, 140, 260))
        self.playerHangman5.setStyleSheet("image: url(:/hangmans/hangman1.png);")
        self.playerHangman5.setText("")
        self.playerHangman5.setObjectName("playerHangman5")
        self.playerNickname1 = QtWidgets.QLabel(GameScreen)
        self.playerNickname1.setGeometry(QtCore.QRect(30, 260, 141, 31))
        self.playerNickname1.setObjectName("playerNickname1")
        self.playerNickname2 = QtWidgets.QLabel(GameScreen)
        self.playerNickname2.setGeometry(QtCore.QRect(210, 260, 141, 31))
        self.playerNickname2.setObjectName("playerNickname2")
        self.playerNickname3 = QtWidgets.QLabel(GameScreen)
        self.playerNickname3.setGeometry(QtCore.QRect(380, 260, 141, 31))
        self.playerNickname3.setObjectName("playerNickname3")
        self.playerNickname4 = QtWidgets.QLabel(GameScreen)
        self.playerNickname4.setGeometry(QtCore.QRect(550, 260, 141, 31))
        self.playerNickname4.setObjectName("playerNickname4")
        self.playerNickname5 = QtWidgets.QLabel(GameScreen)
        self.playerNickname5.setGeometry(QtCore.QRect(730, 260, 141, 31))
        self.playerNickname5.setObjectName("playerNickname5")

        self.retranslateUi(GameScreen)
        QtCore.QMetaObject.connectSlotsByName(GameScreen)

    def retranslateUi(self, GameScreen):
        _translate = QtCore.QCoreApplication.translate
        GameScreen.setWindowTitle(_translate("GameScreen", "Dialog"))
        self.wordLabel.setText(_translate("GameScreen", "TextLabel"))
        self.attemptsLabel.setText(_translate("GameScreen", "attempts"))
        self.usedLettersLabel.setText(_translate("GameScreen", "used letters: "))
        self.playerNickname1.setText(_translate("GameScreen", "playerNickname1"))
        self.playerNickname2.setText(_translate("GameScreen", "playerNickname2"))
        self.playerNickname3.setText(_translate("GameScreen", "playerNickname3"))
        self.playerNickname4.setText(_translate("GameScreen", "playerNickname4"))
        self.playerNickname5.setText(_translate("GameScreen", "playerNickname5"))
import game_images_rc
