# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HangmanGameScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameScreen(object):
    def setupUi(self, GameScreen):
        GameScreen.setObjectName("GameScreen")
        GameScreen.resize(1208, 863)
        self.wordLabel = QtWidgets.QLabel(GameScreen)
        self.wordLabel.setGeometry(QtCore.QRect(260, 460, 661, 131))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.wordLabel.setFont(font)
        self.wordLabel.setObjectName("wordLabel")
        self.attemptsLabel = QtWidgets.QLabel(GameScreen)
        self.attemptsLabel.setGeometry(QtCore.QRect(70, 70, 131, 31))
        self.attemptsLabel.setObjectName("attemptsLabel")
        self.usedLettersLabel = QtWidgets.QLabel(GameScreen)
        self.usedLettersLabel.setGeometry(QtCore.QRect(70, 170, 351, 31))
        self.usedLettersLabel.setObjectName("usedLettersLabel")

        self.retranslateUi(GameScreen)
        QtCore.QMetaObject.connectSlotsByName(GameScreen)

    def retranslateUi(self, GameScreen):
        _translate = QtCore.QCoreApplication.translate
        GameScreen.setWindowTitle(_translate("GameScreen", "Dialog"))
        self.wordLabel.setText(_translate("GameScreen", "TextLabel"))
        self.attemptsLabel.setText(_translate("GameScreen", "attempts"))
        self.usedLettersLabel.setText(_translate("GameScreen", "used letters: "))
