# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scoreui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(240, 231, 239);")
        self.score = QtWidgets.QLabel(Dialog)
        self.score.setGeometry(QtCore.QRect(-50, -10, 491, 321))
        self.score.setStyleSheet("background-image:url(:/text/game_over.png)")
        self.score.setText("")
        self.score.setObjectName("score")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 161, 121))
        self.label.setStyleSheet("image: url(:/text/score.png);\n"
"border: 2px solid rgb(247, 178, 183);\n"
"border-radius: 20px;")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setObjectName("label")
        self.scoreLabel = QtWidgets.QLabel(Dialog)
        self.scoreLabel.setGeometry(QtCore.QRect(180, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setStyleSheet("text-color:rgb(78, 78, 78)")
        self.scoreLabel.setObjectName("scoreLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scoreLabel.setText(_translate("Dialog", "0"))
import ranking_rc
