# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 310)
        self.waitingLabel = QtWidgets.QLabel(Dialog)
        self.waitingLabel.setGeometry(QtCore.QRect(0, 0, 421, 311))
        self.waitingLabel.setStyleSheet("background-image: url(:/waitingImages/waiting.png)")
        self.waitingLabel.setText("")
        self.waitingLabel.setObjectName("waitingLabel")
        self.waitingHangmansLabel = QtWidgets.QLabel(Dialog)
        self.waitingHangmansLabel.setGeometry(QtCore.QRect(0, -10, 461, 251))
        self.waitingHangmansLabel.setStyleSheet("background-image: url(:/waitingImages/hangman8.png)")
        self.waitingHangmansLabel.setText("")
        self.waitingHangmansLabel.setObjectName("waitingHangmansLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Waiting"))
import waitingroom_rc
