# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_WaitingRoom(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 310)
        self.waitingLabel = QtWidgets.QLabel(Dialog)
        self.waitingLabel.setGeometry(QtCore.QRect(0, 0, 421, 311))
        self.waitingLabel.setStyleSheet("background-image: url(:/waitingImages/waiting.png)")
        self.waitingLabel.setText("")
        self.waitingLabel.setObjectName("waitingLabel")
        self.waitingHangmansLabel = QtWidgets.QLabel(Dialog)
        self.waitingHangmansLabel.setGeometry(QtCore.QRect(0, -10, 461, 251))
        self.waitingHangmansLabel.setStyleSheet("background-image: url(:/waitingImages/hangman8.png)")
        self.waitingHangmansLabel.setText("")
        self.waitingHangmansLabel.setObjectName("waitingHangmansLabel")
        self.gameID = QtWidgets.QLabel(Dialog)
        self.gameID.setGeometry(QtCore.QRect(70, 250, 141, 51))
        self.gameID.setStyleSheet("image: url(:/waitingImages/game_id.png)")
        self.gameID.setText("")
        self.gameID.setObjectName("gameID")
        self.gameIDLabel = QtWidgets.QLabel(Dialog)
        self.gameIDLabel.setGeometry(QtCore.QRect(240, 250, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.gameIDLabel.setFont(font)
        self.gameIDLabel.setObjectName("gameIDLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Waiting"))
        self.gameIDLabel.setText(_translate("Dialog", "1"))
import waitingroom_rc
